
exports.EVENTS = {
    LIKE: "LIKE",
    FOLLOW: "FOLLOW",
    MENTION: "MENTION",
    COMMENT: "COMMENT",
    USERS: "USERS",

    ESTABLISH_CONNECTION: "ESTABLISH_CONNECTION",
    NEW_MESSAGE: "NEW_MESSAGE",
    GET_PAGINATED_MSGS: "GET_PAGINATED_MSGS",
    MARK_ALL_READ: "MARK_ALL_READ",
    INIT_CHAT_WITH_MESSAGE: "INIT_CHAT_WITH_MESSAGE",
    ERROR: "ERROR",
    LIKE: "LIKE",
    JOIN_ROOM: "JOIN_ROOM",

    //live STREM ID
    POST_ID: "POST_ID",
    DELTE_STORY: "DELTE_STORY",

    LEAVE_ROOM: "LEAVE_ROOM",
    FOLLOW: "FOLLOW",
    MENTION: "MENTION",
    COMMENT: "COMMENT",
    INIT_OR_GET_CHAT: "INIT_OR_GET_CHAT",

    // HANDLING LIVE SESSION EVENTS =>>>
    LIVE_JOIN_SESSION: "LIVE_JOIN_SESSION",
    LIVE_SESSION_LIKE: "LIVE_SESSION_LIKE",
    LIVE_SESSION_MESSAGE: "LIVE_SESSION_MESSAGE",
    LIVE_SESSION_SHARE: "LIVE_SESSION_SHARE",
    LIVE_SESSION_LEAVE: "LIVE_SESSION_LEAVE",
};