export const REGISTER_SUCCESS = 'REGISTR_SUCCESS'
export const REGISTER_COMPLETE = 'REGISTER_COMPLETE'
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const LOADING = 'LOADING'
export const LOGIN_COMPLETE = 'LOGIN_COMPLETE'
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const FORGOT_PASSWORD_CODE = 'FORGOT_PASSWORD_CODE'
export const RESET_PASSWORD = 'RESET_PASSWORD'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const USER_TYPE = 'USER_TYPE'
export const USER_DATA = 'USER_DATA'
export const SOCIAL_LOGIN = 'SOCIAL_LOGIN'
export const ERROR_MESSAGE = 'ERROR_MESSAGE'
export const BUTTON_LOADING = 'BUTTON_LOADING'
export const LOGIN_TOKEN = 'LOGIN_TOKEN'
export const UPDATE_USERDATA = 'UPDATE_USERDATA'
export const UPDATE_FOLLOWER = 'UPDATE_FOLLOWER'
export const LOGOUT = 'LOGOUT'
export const UPDATE_NOTIFICATION_DATA = 'UPDATE_NOTIFICATION_DATA'
export const TIMER30SEC = 'TIMER30SEC'





